### Exercise 2.A NumPy fundamentals

In [3]:
import numpy as np

# ARRAY BASICS 

In [7]:
fruits = ['apple', 'banana', 'cherry', 'date']
print(fruits)

['apple', 'banana', 'cherry', 'date']


In [9]:
arr_1= np.array(fruits)
arr_1

array(['apple', 'banana', 'cherry', 'date'], dtype='<U6')

In [10]:
## datatype is U6. U stands for unicode and 6 stands for the number of strings

In [21]:
arr_2 =np.array([[10,11,12],[13,14,15]])
arr_2


array([[10, 11, 12],
       [13, 14, 15]])

In [18]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [22]:
## it does alter the value a little bit as know the two arrays joins and we get each same index like first of the first and first of the second and second of the second and second of the first


In [29]:
arr_3 =np.array([[1,3,5],[2,4,6]])
arr_4= np.array([arr_3[0,2], arr_3[1,1]])
arr_4


array([5, 4])

In [39]:
arr_5= np.array([[[1,1],[1,1]],[[1,1],[1,1]]])


3
